/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                                           \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>

// 0x4002 0400 GPIOB
// 0x4002 0414 GPIOB_ODR
// 0x4002 3800 RCC
// 0x4002 3830 RCC_AHB1ENR
// LED on PB8

int main(void)
{
    // enable GPIOB
    *((volatile uint32_t*)(0x40023830)) |= (1 << 1);
    // configure GPIO PB8 as output
    *((volatile uint32_t*)(0x40020400)) |= (1 << 16);
    for (;;)
    {
        *((volatile uint32_t*)(0x40020414)) = *((volatile uint32_t*)(0x40020414)) xor (1 << 8);
        for (volatile int i = 0; i < 1024 * 1024 * 2; i++)
            ;
    }
}
