/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                                           \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../../ucpp/register.hpp"
#include "../../ucpp/stm32/gpio.hpp"
#include "../../ucpp/stm32/rcc.hpp"
#include "../../ucpp/stm32/stm32f7.hpp"
#include "../../ucpp/strong_types.hpp"

using namespace ucpp::stm32;
reg_t<uint16_t, 0x1FF0F442, read_only> flash_size_ro;
reg_t<uint16_t, 0x1FF0F442, read_write> flash_size_rw;

int main(void)
{
    flash_size_rw = 10;
    //flash_size_ro = 10;
    gpio::mode_field<3>(stm32f7.GPIOK)
            = gpio::mode::output;
    for (;;)
    {
    }
}
